# Generated by Django 3.2.6 on 2021-08-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Add a comment', max_length=200),
        ),
    ]
