# Generated by Django 4.0.1 on 2022-01-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('notes', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.author'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.author'),
        ),
        migrations.AlterField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(related_name='author_comments', through='notes.Comment', to='users.Author'),
        ),
        migrations.AlterField(
            model_name='note',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='users.Author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
