# Generated by Django 3.2.6 on 2021-08-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesrepo', '0002_rename_owner_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesrepo.author')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesrepo.note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(related_name='author_comments', through='notesrepo.Comment', to='notesrepo.Author'),
        ),
    ]
