# Generated by Django 3.2.6 on 2021-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesrepo', '0003_auto_20210809_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
