# Generated by Django 3.2.6 on 2021-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesrepo', '0004_rename_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='notesrepo.Author'),
        ),
    ]
