# Generated by Django 3.2.5 on 2021-07-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesrepo', '0002_alter_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='slug',
        ),
    ]
